function ch = open_can_channel()
global ch db
%% Auto-generated by Vehicle Network Toolbox CAN Explorer on 05-May-2024 16:13:27.
%% Introduction
% This script is usable outside of CAN Explorer to replicate its actions. You 
% cannot use this script to reconfigure the app. The script demonstrates the MATLAB® 
% command line workflow using functions provided in Vehicle Network Toolbox™. 
% You can modify it to build your own script, function, or application.
%% Create a CAN Channel
% Create a CAN channel connection using the specified device.

ch = canChannel("Vector", "CANcaseXL log 1", 1)
%% Configure the Channel Bus Speed
% If the channel has full control of the device, set the bus speed.

if ch.InitializationAccess
    configBusSpeed(ch, 1000000)
end
%% Configure the Message Filters
% Use message filters to control which messages pass through the channel.

filterAllowOnly(ch, [385 386 641], 'Standard')
%% Open the DBC-File
% Open the DBC-file for use.

db = canDatabase("Rolli.dbc")
%% Attach the Database to the Channel
% Attach the database directly to the channel. Definitions from this database 
% are applied automatically to decode incoming messages and signals.

ch.Database = db
%% Start the Channel
% Start the channel to establish an online connection.

start(ch)
end